name: Main

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  unit_tests_windows:
    name: Windows, Build & Unit Testing
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      #- name: Compile Visual Studio project with MSBuild
        #shell: cmd 
        #run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild' }}
        #working-directory: .

      - name: Show cwd and checkout
        shell: cmd
        run: dir .